# Generated by Django 2.2.9 on 2020-02-21 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('numero_de_telephone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être entré au format: '+22587147883'. le code pays(+225) suivi de votre numero.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_de_naissance', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('domicile', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('quartier', models.CharField(max_length=200)),
            ],
        ),
    ]
